spring.application.name=FileStorage
spring.r2dbc.url=${DATABASE_URL:r2dbc:postgresql://localhost:5433/filestorage}
spring.r2dbc.username=${DATABASE_USERNAME:filestorage}
spring.r2dbc.password=${DATABASE_PASSWORD:filestorage}
spring.sql.init.mode=always

spring.webflux.multipart.max-in-memory-size=1MB
spring.webflux.multipart.max-disk-usage-per-part=${MAX_UPLOAD_SIZE:1GB}
spring.webflux.multipart.max-parts=2

app.storage.file-root=${FILE_STORAGE_ROOT:data/uploads}
server.port=${SERVER_PORT:8081}
