spring.application.name=FileStorage
spring.r2dbc.url=r2dbc:postgresql://localhost:5433/filestorage
spring.r2dbc.username=filestorage
spring.r2dbc.password=filestorage
spring.sql.init.mode=always

app.storage.file-root=data/uploads
server.port=8081